apiVersion: apps/v1
kind: Deployment
metadata:
  name: myappcontainer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myappcontainer
  template:
    metadata:
      labels:
        app: myappcontainer
    spec:
      containers:
        - name: myappcontainer
          image: ghassen007/devops
---
apiVersion: v1
kind: Service
metadata:
  name: myappcontainer
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 80
  type: NodePort    
  selector:
    apps: myappcontainer
