- name: log into docker hub registy
  docker_login:
    email: ghassen.riahi@esprit.tn
    password: dckr_pat_IFg4wpgGbvGCjcsic05GJ6N6jWI
- name: Tag and push to docker hub
  docker_image:
    name: devops
    repository: ghassen007/devops
    push: yes
    source: local
